version: "3"

services:
  node:
    image: node:16
    user: node
    working_dir: /usr/src/app
    volumes:
      - $PWD:/usr/src/app
    command: yarn storybook
    ports:
      - 3000:3000
      
  nginx:
    image: nginx:1.24.0
    volumes:
      - $PWD/docs:/usr/share/nginx/html
    ports:
      - 8080:80