services:
  storybook:
    image: node:20
    working_dir: /home/node/storybook
    volumes:
      - $PWD:/home/node/storybook
    user: node
    command: yarn serve:storybook
    ports:
      - 3000:3000

  integration:
    image: node:20
    working_dir: /home/node/app
    volumes:
      - $PWD:/home/node/app
    user: node
    command: yarn serve:integration
    ports:
      - 4000:4000

  nginx:
    image: nginx:1.24.0
    volumes:
      - $PWD/storybook-static:/usr/share/nginx/html
    ports:
      - 8080:80